In [ ]:
import numpy as np
import pandas as pd
import nltk
import spacy
import string

In [ ]:
df = pd.read_csv("/content/twcs.csv")

/tmp/ipykernel_8596/706236439.py:1: DtypeWarning: Columns (1,2,3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/twcs.csv")

In [ ]:
df

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1.0,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2.0,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3.0,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4.0,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5.0,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0
...,...,...,...,...,...,...,...
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df[["text"]]

In [ ]:
df

                                                      text
0        @115712 I understand. I would like to assist y...
1            @sprintcare and how do you propose we do that
2        @sprintcare I have sent several private messag...
3        @115712 Please send us a Private Message so th...
4                                       @sprintcare I did.
...                                                    ...
1048569                                                NaN
1048570                                                NaN
1048571                                                NaN
1048572                                                NaN
1048573                                                NaN

[1048574 rows x 1 columns]

In [ ]:
df["text"].str.lower()

0          @115712 i understand. i would like to assist y...
1              @sprintcare and how do you propose we do that
2          @sprintcare i have sent several private messag...
3          @115712 please send us a private message so th...
4                                         @sprintcare i did.
                                 ...
1048569                                                  NaN
1048570                                                  NaN
1048571                                                  NaN
1048572                                                  NaN
1048573                                                  NaN
Name: text, Length: 1048574, dtype: object

In [ ]:
punc = string.punctuation

In [ ]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_puncituation(text):
  return text.translate(str.maketrans('','',punc))

df.loc[:, 'text'] = df['text'].fillna('') # Fill NaN values with empty strings
df.loc[:, "text_without_punc"] = df['text'].apply(lambda text : remove_puncituation(text))

/tmp/ipykernel_8596/970883590.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].fillna('') # Fill NaN values with empty strings
/tmp/ipykernel_8596/970883590.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_without_punc"]=df['text'].apply(lambda text : remove_puncituation(text))

In [ ]:
df

,text,text_without_punc
0,@115712 I understand. I would like to assist y...,115712 I understand I would like to assist you...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,sprintcare I have sent several private message...
3,@115712 Please send us a Private Message so th...,115712 Please send us a Private Message so tha...
4,@sprintcare I did.,sprintcare I did
...,...,...
1048569,,
1048570,,
1048571,,
1048572,,
1048573,,

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words("english"))
STOPWORDS

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [ ]:
def remove_stopwords(text):
  return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df["text_without_stopwords"] = df["text_without_punc"].apply(lambda text : remove_stopwords(text))

/tmp/ipykernel_8596/2489503073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_without_stopwords"] = df["text_without_punc"].apply(lambda text : remove_stopwords(text))

In [ ]:
df

,text,text_without_punc,text_without_stopwords
0,@115712 I understand. I would like to assist y...,115712 I understand I would like to assist you...,115712 I understand I would like assist We wou...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose
2,@sprintcare I have sent several private messag...,sprintcare I have sent several private message...,sprintcare I sent several private messages one...
3,@115712 Please send us a Private Message so th...,115712 Please send us a Private Message so tha...,115712 Please send us Private Message assist J...
4,@sprintcare I did.,sprintcare I did,sprintcare I
...,...,...,...
1048569,,,
1048570,,,
1048571,,,
1048572,,,
1048573,,,

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()


def stem_words(text):
  return " ".join([stemmer.stem(word)for word in text.split()])

df["text_stemmed"] = df['text_without_stopwords'].apply(lambda text : stem_words(text))

/tmp/ipykernel_8596/3122185515.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_stemmed"] = df['text_without_stopwords'].apply(lambda text : stem_words(text))

In [ ]:
df

,text,text_without_punc,text_without_stopwords,text_stemmed
0,@115712 I understand. I would like to assist y...,115712 I understand I would like to assist you...,115712 I understand I would like assist We wou...,115712 i understand i would like assist we wou...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcar propos
2,@sprintcare I have sent several private messag...,sprintcare I have sent several private message...,sprintcare I sent several private messages one...,sprintcar i sent sever privat messag one respo...
3,@115712 Please send us a Private Message so th...,115712 Please send us a Private Message so tha...,115712 Please send us Private Message assist J...,115712 pleas send us privat messag assist just...
4,@sprintcare I did.,sprintcare I did,sprintcare I,sprintcar i
...,...,...,...,...
1048569,,,,
1048570,,,,
1048571,,,,
1048572,,,,
1048573,,,,

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download("wordnet")
lemmatizer = WordNetLemmatizer()

def lemmize_words(text):
  return " ".join([lemmatizer.lemmatize(word)for word in str(text).split()])

df["text_lemmatized"] = df["text_without_stopwords"].apply(lambda text : lemmize_words(text))

[nltk_data] Downloading package wordnet to /root/nltk_data...
/tmp/ipykernel_8596/292666052.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_lemmatized"] = df["text_without_stopwords"].apply(lambda text : lemmize_words(text))

In [ ]:
df

,text,text_without_punc,text_without_stopwords,text_stemmed,text_lemmatized
0,@115712 I understand. I would like to assist y...,115712 I understand I would like to assist you...,115712 I understand I would like assist We wou...,115712 i understand i would like assist we wou...,115712 I understand I would like assist We wou...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcar propos,sprintcare propose
2,@sprintcare I have sent several private messag...,sprintcare I have sent several private message...,sprintcare I sent several private messages one...,sprintcar i sent sever privat messag one respo...,sprintcare I sent several private message one ...
3,@115712 Please send us a Private Message so th...,115712 Please send us a Private Message so tha...,115712 Please send us Private Message assist J...,115712 pleas send us privat messag assist just...,115712 Please send u Private Message assist Ju...
4,@sprintcare I did.,sprintcare I did,sprintcare I,sprintcar i,sprintcare I
...,...,...,...,...,...
1048569,,,,,
1048570,,,,,
1048571,,,,,
1048572,,,,,
1048573,,,,,